version: '3'
services:
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/sample_app/public
      - tmp-data:/sample_app/tmp
    ports:
      - 80:80
    depends_on:
      - app

  app:
    build:
      context: .
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    environment:
      RAILS_ENV: development
    volumes:
      - .:/sample_app
      - public-data:/sample_app/public
      - tmp-data:/sample_app/tmp
      - log-data:/sample_app/log
    ports:
      - "3000:3000"
    links:
      - db

  db:
    image: mysql:5.7
    env_file:
      - ./environments/db.env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: